apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme
  template:
    metadata:
      labels:
        app: meme
    spec:
      containers:
        - name: meme
          image: meme:1.0.0
          ports:
            - containerPort: 9090
          env:
            - name: QUOTE_URL
              value: "2341039a0sdfa"
              name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  key: "pass"
---
kind: Service
apiVersion: v1
metadata:
  name: meme
  labels:
    app: meme
spec:
  selector:
    app: meme
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
