FROM golang:1.11.4-alpine3.8 as builder

ENV BASE_APP_DIR /go/src/github.com/mszostok/k8s-lecture
WORKDIR ${BASE_APP_DIR}

#
# Copy files
#

COPY ./vendor/ ${BASE_APP_DIR}/vendor/
COPY ./internal/ ${BASE_APP_DIR}/internal/
COPY ./cmd/ ${BASE_APP_DIR}/cmd/

#
# Build app
#

RUN cd cmd/meme && env CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -v -o srv . && mv ./srv /srv

FROM alpine:3.8

#
# Copy binary
#

COPY --from=builder /srv /srv

#
# Run app
#

CMD ["/srv"]
